package com.narve.model;// default package
// Generated 05-Dec-2025, 11:46:40 am by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,schema="public"
)
public class Address implements java.io.Serializable {


     private int addressId;
     private Employee employee;
     private String houseNo;
     private String street;
     private String country;
     private String stateOfCountry;
     private String zipcode;

    public Address() {
    }

	
    public Address(int addressId, String houseNo, String street, String country, String stateOfCountry, String zipcode) {
        this.addressId = addressId;
        this.houseNo = houseNo;
        this.street = street;
        this.country = country;
        this.stateOfCountry = stateOfCountry;
        this.zipcode = zipcode;
    }
    public Address(int addressId, Employee employee, String houseNo, String street, String country, String stateOfCountry, String zipcode) {
       this.addressId = addressId;
       this.employee = employee;
       this.houseNo = houseNo;
       this.street = street;
       this.country = country;
       this.stateOfCountry = stateOfCountry;
       this.zipcode = zipcode;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="address_id", unique=true, nullable=false)
    public int getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="house_no", nullable=false, length=50)
    public String getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }

    
    @Column(name="street", nullable=false, length=50)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="country", nullable=false, length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="state_of_country", nullable=false, length=50)
    public String getStateOfCountry() {
        return this.stateOfCountry;
    }
    
    public void setStateOfCountry(String stateOfCountry) {
        this.stateOfCountry = stateOfCountry;
    }

    
    @Column(name="zipcode", nullable=false, length=10)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }




}


