package com.narve.model;// default package
// Generated 05-Dec-2025, 11:46:40 am by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,schema="public"
)
public class Department implements java.io.Serializable {


     private int departmentId;
     private String departmentName;
     private String departmentLocation;
     private LocalDate createdDate;
     private LocalDate updatedDate;
     private Set<Employee>  employees = new HashSet(0);

    public Department() {
    }

	
    public Department(int departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }
    public Department(int departmentId, String departmentName, String departmentLocation, LocalDate createdDate, LocalDate updatedDate, Set employees) {
       this.departmentId = departmentId;
       this.departmentName = departmentName;
       this.departmentLocation = departmentLocation;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.employees = employees;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="department_id", unique=true, nullable=false)
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="department_name", nullable=false, length=50)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="department_location", length=50)
    public String getDepartmentLocation() {
        return this.departmentLocation;
    }
    
    public void setDepartmentLocation(String departmentLocation) {
        this.departmentLocation = departmentLocation;
    }


    @Column(name="created_date", length=29)
    public LocalDate getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="updated_date", length=29)
    public LocalDate getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(LocalDate updatedDate) {
        this.updatedDate = updatedDate;
    }

   @OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


